// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: examples/foo.proto

package wrapper_examples

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/marbar3778/go-proto-wrapper"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FooMsg) Unwrap() (proto.Message, error) {
	switch msg := this.Sum.(type) {
	case *FooMsg_Foo:
		return this.GetFoo(), nil
	case *FooMsg_Bar:
		return this.GetBar(), nil
	case *FooMsg_Baz:
		return this.GetBaz(), nil
	default:
		return nil, fmt.Errorf("unknown message: %T", msg)
	}
}

func (this *FooMsg) Wrap(msg proto.Message) error {
	if msg == nil {
		this.Sum = nil
		return nil
	}
	switch vt := msg.(type) {
	case *Foo:
		this.Sum = &FooMsg_Foo{vt}
	case *Bar:
		this.Sum = &FooMsg_Bar{vt}
	case *Baz:
		this.Sum = &FooMsg_Baz{vt}
	default:
		return fmt.Errorf("unknown message: %T", msg)
	}
	return nil
}
