// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: examples/item.proto

package wrapper_examples

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Items struct {
	// Types that are valid to be assigned to Sum:
	//	*Items_Item
	//	*Items_Object
	//	*Items_Value
	Sum                  isItems_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_e752296231b70535, []int{0}
}
func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (m *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(m, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

type isItems_Sum interface {
	isItems_Sum()
}

type Items_Item struct {
	Item *Item `protobuf:"bytes,1,opt,name=item,proto3,oneof" json:"item,omitempty"`
}
type Items_Object struct {
	Object *Object `protobuf:"bytes,2,opt,name=object,proto3,oneof" json:"object,omitempty"`
}
type Items_Value struct {
	Value *Value `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (*Items_Item) isItems_Sum()   {}
func (*Items_Object) isItems_Sum() {}
func (*Items_Value) isItems_Sum()  {}

func (m *Items) GetSum() isItems_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *Items) GetItem() *Item {
	if x, ok := m.GetSum().(*Items_Item); ok {
		return x.Item
	}
	return nil
}

func (m *Items) GetObject() *Object {
	if x, ok := m.GetSum().(*Items_Object); ok {
		return x.Object
	}
	return nil
}

func (m *Items) GetValue() *Value {
	if x, ok := m.GetSum().(*Items_Value); ok {
		return x.Value
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Items) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Items_Item)(nil),
		(*Items_Object)(nil),
		(*Items_Value)(nil),
	}
}

type Item struct {
	A                    uint64   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_e752296231b70535, []int{1}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetA() uint64 {
	if m != nil {
		return m.A
	}
	return 0
}

type Object struct {
	A                    uint64   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_e752296231b70535, []int{2}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetA() uint64 {
	if m != nil {
		return m.A
	}
	return 0
}

type Value struct {
	A                    uint64   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_e752296231b70535, []int{3}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetA() uint64 {
	if m != nil {
		return m.A
	}
	return 0
}

func init() {
	proto.RegisterType((*Items)(nil), "wrapper.examples.Items")
	proto.RegisterType((*Item)(nil), "wrapper.examples.item")
	proto.RegisterType((*Object)(nil), "wrapper.examples.object")
	proto.RegisterType((*Value)(nil), "wrapper.examples.value")
}

func init() { proto.RegisterFile("examples/item.proto", fileDescriptor_e752296231b70535) }

var fileDescriptor_e752296231b70535 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x2d, 0xd6, 0xcf, 0x2c, 0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x28, 0x2f, 0x4a, 0x2c, 0x28, 0x48, 0x2d, 0xd2, 0x83, 0x49, 0x2a, 0x2d, 0x64, 0xe4, 0x62,
	0xf5, 0x2c, 0x49, 0xcd, 0x2d, 0x16, 0xd2, 0xe1, 0x62, 0x01, 0xa9, 0x94, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x36, 0x12, 0xd3, 0x43, 0x57, 0xaa, 0x07, 0x92, 0xf5, 0x60, 0x08, 0x02, 0xab, 0x12, 0x32,
	0xe2, 0x62, 0xcb, 0x4f, 0xca, 0x4a, 0x4d, 0x2e, 0x91, 0x60, 0x02, 0xab, 0x97, 0xc0, 0x54, 0x0f,
	0x91, 0xf7, 0x60, 0x08, 0x82, 0xaa, 0x14, 0xd2, 0xe7, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95,
	0x60, 0x06, 0x6b, 0x11, 0xc7, 0xd4, 0x02, 0x96, 0xf6, 0x60, 0x08, 0x82, 0xa8, 0x73, 0x62, 0xe5,
	0x62, 0x2e, 0x2e, 0xcd, 0x55, 0x12, 0x81, 0xb8, 0x4c, 0x88, 0x87, 0x8b, 0x31, 0x11, 0xec, 0x3c,
	0x96, 0x20, 0xc6, 0x44, 0x25, 0x31, 0x98, 0x0b, 0xd0, 0xc4, 0x45, 0xa1, 0xb6, 0xa0, 0x0a, 0x27,
	0xb1, 0x81, 0x43, 0xc0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x61, 0x44, 0xb2, 0x0e, 0x18, 0x01,
	0x00, 0x00,
}
